FROM 1234 nag / loadgenerator : latest
ADD ./ NASA_DAY.csv /
ADD ./ FIFA_DAY.csv /
ADD ./ NASA_DAY.sh /
ADD ./ FIFA_DAY.sh /
ADD ./ NASA_Repeat.csv /
ADD ./ RandomFIFA.csv /
ADD ./ NASA_Repeat.sh /
ADD ./ RandomFIFA.sh /
RUN chmod + r / NASA_DAY.csv
RUN chmod + r / NASA_DAY.sh
RUN chmod + r / FIFA_DAY.csv
RUN chmod + r / FIFA_DAY.sh
RUN chmod + r / NASA_Repeat.csv
RUN chmod + r / NASA_Repeat.sh
RUN chmod + r / RandomFIFA.csv
RUN chmod + r / RandomFIFA.sh
